-- Resume Upload → OCR → Structured Extraction Pipeline (Alpha)
-- Not applied via `supabase db push` (this project has no migrations history / CLI linkage yet —
-- every prior schema change this project has had was run ad hoc through the dashboard SQL editor,
-- confirmed by `git log --diff-filter=A -- '*.sql'` returning nothing before this file). Committed
-- here as the durable record of what was run, and it *is* run through the same dashboard SQL
-- editor as everything else, verified with a real query against information_schema afterward —
-- same discipline as every other piece of this build.

-- === Storage: private bucket for resume documents ===
-- Private (public = false): originals and sanitized renders are only ever served via signed URLs
-- generated by service-role Edge Functions, never a public bucket URL.
insert into storage.buckets (id, name, public)
values ('resume-documents', 'resume-documents', false)
on conflict (id) do nothing;

-- === Schema ===

-- candidate_id starts NULL and stays that way until confirm-verification backfills it. This
-- mirrors the existing phone/full_name pattern exactly: collected pre-confirmation, staged on the
-- email_verifications row, only written into `candidates` at confirm time. candidates rows are
-- deliberately created only at confirm time (same zero-trace-for-abandoned-signups hygiene used
-- elsewhere in this project) — resume uploads happen at isEntry/isPreview, before that row exists,
-- so they're staged against email_verification_id instead. email_verification_id has NO hard FK
-- constraint, matching the exact same reasoning already used for candidates.verification_id
-- (confirmed live: `candidates.verification_id uuid`, no FK) — email_verifications rows are
-- logically expired via their own expires_at (checked in confirm-verification) rather than
-- physically deleted by any automated job found in this project (checked live: no pg_cron
-- extension installed, no scheduled cleanup Edge Function among this project's 20 deployed
-- functions — "14-day cleanup" is currently a soft-expiry policy, not an automated physical sweep;
-- see cleanup_expired_unconfirmed_resume_data() below, which extends that same soft-expiry
-- principle and additionally provides a real, callable hard-delete, ready to wire into a scheduler
-- whenever this project adds one — not claiming one already exists).
create table resume_documents (
  id uuid primary key default gen_random_uuid(),
  candidate_id uuid references candidates(id),
  email_verification_id uuid,            -- staging key before candidate_id is backfilled
  original_storage_path text not null,   -- untouched original bytes, permanent, document of record
  original_filename text,
  mime_type text,
  sanitized_render_path text,            -- flattened/EXIF-stripped image; only thing OCR touches
  ocr_raw_text text,
  extraction_status text not null default 'pending', -- pending | ocr_done | extracted | failed
  uploaded_at timestamptz not null default now(),
  extracted_at timestamptz
);

create table work_history_items (
  id uuid primary key default gen_random_uuid(),
  candidate_id uuid references candidates(id),
  resume_document_id uuid references resume_documents(id),
  company text, title text, start_date date, end_date date,
  job_responsibilities text,
  status text not null default 'Not Submitted for Verification',
  candidate_confirmed boolean not null default false,
  extraction_confidence text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table education_items (
  id uuid primary key default gen_random_uuid(),
  candidate_id uuid references candidates(id),
  resume_document_id uuid references resume_documents(id),
  institution text, degree text, field_of_study text, start_date date, end_date date,
  status text not null default 'Not Submitted for Verification',
  candidate_confirmed boolean not null default false,
  extraction_confidence text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table certification_items (
  id uuid primary key default gen_random_uuid(),
  candidate_id uuid references candidates(id),
  resume_document_id uuid references resume_documents(id),
  name text, issuing_body text, issue_date date, expiration_date date,
  status text not null default 'Not Submitted for Verification',
  candidate_confirmed boolean not null default false,
  extraction_confidence text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table candidate_freeform_sections (
  id uuid primary key default gen_random_uuid(),
  candidate_id uuid references candidates(id),
  resume_document_id uuid references resume_documents(id),
  section_type text not null,  -- 'summary' | 'hobbies_other' | 'needs_review'
  content text,
  candidate_confirmed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

-- Status values on the four item tables above must match the Item 18 model exactly:
--   'Verified', 'Candidate-stated-not-independently-verified', 'Unable to Verify',
--   'Discrepancies Not Resolved', 'Not Submitted for Verification'
-- This is a DIFFERENT axis from verification_items.status (the staff-queue workflow status —
-- confirmed live: real values in use today are New / In Progress / Awaiting Response /
-- Needs Reconciliation / Confirmed / Discrepancy / Unable to Verify, matching staff.html's
-- STATUS_OPTIONS array exactly). The two never need to match each other: work_history_items.status
-- etc. describes "has this specific candidate-asserted fact been verified," staying
-- 'Not Submitted for Verification' until a category is opted into the staff queue (at which point
-- confirm-resume-data inserts a fresh verification_items row, status defaulting to 'New' as usual —
-- work_history_items.status is not touched by that insert in this build; wiring staff resolution
-- back to flip it to 'Verified' etc. is a real next step, explicitly not built here).

-- === ID generation for new verification_items rows ===
-- Real existing rows use a "VQ-####" id (verification_items.id is `text`, not uuid — confirmed live
-- via `select id,type,status,claim from verification_items limit 8`, e.g. "VQ-1034 | Job Experience
-- | Unable to Verify | ..."). The function/flow that originally generated these wasn't reachable
-- before this session's browser tool connection dropped mid-build, so this is a considered
-- decision, not a reverse-engineered match: a dedicated sequence producing same-shaped, guaranteed-
-- unique ids, used by confirm-resume-data below.
create sequence if not exists verification_item_id_seq start with 2000;

create or replace function nextval_verification_item_id() returns text
language sql
security definer
set search_path = public
as $$
  select 'VQ-' || nextval('verification_item_id_seq')::text;
$$;

grant execute on function nextval_verification_item_id() to service_role;

-- === Atomic multi-table insert for extract-resume-fields ===
-- "never partial-inserts" (build spec) needs a real transaction across four tables. The Supabase
-- JS client's REST calls each commit independently — there is no ad-hoc multi-table transaction
-- available from an Edge Function without one. A single Postgres function's body runs inside one
-- transaction implicitly: any exception here rolls back every insert this call made, atomically.
-- extract-resume-fields calls this once, after it has already parsed and fully validated Claude's
-- JSON response — so this function never has to handle malformed LLM output itself, only insert it.
create or replace function insert_resume_extraction(
  p_resume_document_id uuid,
  p_candidate_id uuid,
  p_work_history jsonb,    -- array of {company,title,start_date,end_date,job_responsibilities,extraction_confidence}
  p_education jsonb,       -- array of {institution,degree,field_of_study,start_date,end_date,extraction_confidence}
  p_certifications jsonb,  -- array of {name,issuing_body,issue_date,expiration_date,extraction_confidence}
  p_freeform jsonb         -- array of {section_type,content}
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into work_history_items (candidate_id, resume_document_id, company, title, start_date, end_date, job_responsibilities, extraction_confidence)
  select p_candidate_id, p_resume_document_id, r.company, r.title,
         nullif(r.start_date,'')::date, nullif(r.end_date,'')::date, r.job_responsibilities, r.extraction_confidence
  from jsonb_to_recordset(p_work_history) as r(company text, title text, start_date text, end_date text, job_responsibilities text, extraction_confidence text);

  insert into education_items (candidate_id, resume_document_id, institution, degree, field_of_study, start_date, end_date, extraction_confidence)
  select p_candidate_id, p_resume_document_id, r.institution, r.degree, r.field_of_study,
         nullif(r.start_date,'')::date, nullif(r.end_date,'')::date, r.extraction_confidence
  from jsonb_to_recordset(p_education) as r(institution text, degree text, field_of_study text, start_date text, end_date text, extraction_confidence text);

  insert into certification_items (candidate_id, resume_document_id, name, issuing_body, issue_date, expiration_date, extraction_confidence)
  select p_candidate_id, p_resume_document_id, r.name, r.issuing_body,
         nullif(r.issue_date,'')::date, nullif(r.expiration_date,'')::date, r.extraction_confidence
  from jsonb_to_recordset(p_certifications) as r(name text, issuing_body text, issue_date text, expiration_date text, extraction_confidence text);

  insert into candidate_freeform_sections (candidate_id, resume_document_id, section_type, content)
  select p_candidate_id, p_resume_document_id, r.section_type, r.content
  from jsonb_to_recordset(p_freeform) as r(section_type text, content text);
end;
$$;

grant execute on function insert_resume_extraction(uuid, uuid, jsonb, jsonb, jsonb, jsonb) to service_role;

-- === Backfill candidate_id once confirm-verification creates the real candidate row ===
-- Called once from confirm-verification, right after the existing insert-then-PATCH sequence
-- (candidates insert, then email_verifications.confirmed_at PATCH). One RPC covering the full
-- cascade (resume_documents + all 4 child tables, joined through resume_document_id) so there is no
-- reachable state where a confirmed candidate has orphaned resume rows or vice versa. If this call
-- fails, confirm-verification still returns success for the signup itself — a resume-pipeline
-- problem should never block account confirmation — and reports resume_backfill_error in its
-- response instead of swallowing it.
create or replace function backfill_resume_pipeline_candidate_id(
  p_email_verification_id uuid,
  p_candidate_id uuid
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update resume_documents set candidate_id = p_candidate_id
  where email_verification_id = p_email_verification_id and candidate_id is null;

  update work_history_items set candidate_id = p_candidate_id
  where resume_document_id in (select id from resume_documents where email_verification_id = p_email_verification_id)
    and candidate_id is null;

  update education_items set candidate_id = p_candidate_id
  where resume_document_id in (select id from resume_documents where email_verification_id = p_email_verification_id)
    and candidate_id is null;

  update certification_items set candidate_id = p_candidate_id
  where resume_document_id in (select id from resume_documents where email_verification_id = p_email_verification_id)
    and candidate_id is null;

  update candidate_freeform_sections set candidate_id = p_candidate_id
  where resume_document_id in (select id from resume_documents where email_verification_id = p_email_verification_id)
    and candidate_id is null;
end;
$$;

grant execute on function backfill_resume_pipeline_candidate_id(uuid, uuid) to service_role;

-- === Extends the existing soft-expiry policy to a real, callable hard-delete ===
-- Not currently invoked by anything automated (see the note on resume_documents above — no
-- pg_cron, no scheduled cleanup function found in this project today). Provided so an abandoned
-- signup's uploaded resume content doesn't sit around indefinitely once a real scheduler exists;
-- until then, it can be run manually or wired to a call from any function that already touches
-- expired rows.
create or replace function cleanup_expired_unconfirmed_resume_data() returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ids uuid[];
begin
  select array_agg(rd.id) into v_ids
  from resume_documents rd
  join email_verifications ev on ev.id = rd.email_verification_id
  where rd.candidate_id is null and ev.confirmed_at is null and ev.expires_at < now();

  if v_ids is null then return; end if;

  delete from work_history_items where resume_document_id = any(v_ids);
  delete from education_items where resume_document_id = any(v_ids);
  delete from certification_items where resume_document_id = any(v_ids);
  delete from candidate_freeform_sections where resume_document_id = any(v_ids);
  delete from resume_documents where id = any(v_ids);
  -- Storage objects (original_storage_path / sanitized_render_path) are not deleted here — a
  -- Postgres function can't reach Supabase Storage directly. A real scheduled job would need to
  -- list and remove those objects via the Storage API first; flagged, not silently incomplete.
end;
$$;

grant execute on function cleanup_expired_unconfirmed_resume_data() to service_role;

-- REMINDER (real gotcha hit earlier this project): grant service_role explicitly, table creation
-- alone is not enough.
grant select, insert, update on table resume_documents to service_role;
grant select, insert, update on table work_history_items to service_role;
grant select, insert, update on table education_items to service_role;
grant select, insert, update on table certification_items to service_role;
grant select, insert, update on table candidate_freeform_sections to service_role;
grant usage on sequence verification_item_id_seq to service_role;
